name: eslint
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run eslint
        run: make lint
