name: eslint
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: make install
      - run: make lint
